### ISSUE TITLE
bad syntax in actions file

### ISSUE THREAD

**Issue by wrycu** [League-of-Foundry-Developers/FoundryVTT-Module-Template#24]
The URL rewriting on lines 98-100 of https://github.com/League-of-Foundry-Developers/FoundryVTT-Module-Template/blob/master/.github/workflows/main.yml#L98-L100 say:

```yaml
URL: ${{ $env.project_url }}
MANIFEST: ${{ $env.latest_manifest_url }}
DOWNLOAD: ${{ $env.release_module_url }}
```

which is not correct and results in a failure to execute the action. removing the $ before env works:
```yml
URL: ${{ env.project_url }}
MANIFEST: ${{ env.latest_manifest_url }}
DOWNLOAD: ${{ env.release_module_url }}
```
